# I do not wish to receive email notifications
notifications:
  email: false


# Use a custom build infrastructure
# See  https://github.com/hvr/multi-ghc-travis
language: c

# Use new container infrastructure to enable caching
sudo: false

# convenient abbreviation
env:
  global:
    - PKGNAME=secd

# build matrix
matrix:
  include:
    - env: CABALVER=1.22 GHCVER=7.10.1
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1], sources: [hvr-ghc]}}
    - env: CABALVER=1.24 GHCVER=8.0.1
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1],  sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
  - cabal install hspec
  - cabal install --only-dependencies

before_script:
  - cabal configure
  - cabal sdist
  - cd ..
  - tar -xf $PKGNAME/dist/$PKGNAME*.tar.gz
  - cd $PKGNAME*

script:
  - cabal configure --enable-tests && cabal build && cabal test
